### PR TITLE
[Manta]  wasm benchmark

### PR DESCRIPTION
**Pull request by zhenfeizhang**

### CODE REVIEW

**Comment by stechu** [comment]
@ghzlatarev  thanks! for the substrate related crates, right now we keep it consistent with the v3.0.0 released. For others, it is indeed doesn't hurt to update to newer version if this didn't break anything.

**Comment by stechu** [comment]
For example, upgrade `chacha` to `3.0` will break the code. There is probably a way to handle the the upgrade, though. Feel free to take a look and submit a PR :)

**Review by stechu — APPROVED** [review]

**Comment by zhenfeizhang** [comment]
> There are some crates which aren't latest version like:
> `criterion = "0.2"` or `rand_chacha = { version = "0.2", default-features = false }`
> Is that on purpose ?

Yeah... I also tried to update the dependencies...
those two will break the code. we may take another look at them at a later time.
criterion is an easy fix -- all we need to do is to update our own benchmark file
rand_chacha is really tricky. the rng related traits are not compatible with arkwork's rng trait

**Comment by ghzlatarev** [comment]
> > There are some crates which aren't latest version like:
> > `criterion = "0.2"` or `rand_chacha = { version = "0.2", default-features = false }`
> > Is that on purpose ?
> 
> Yeah... I also tried to update the dependencies...
> those two will break the code. we may take another look at them at a later time.
> criterion is an easy fix -- all we need to do is to update our own benchmark file
> rand_chacha is really tricky. the rng related traits are not compatible with arkwork's rng trait

Gotcha. I'm gonna log this and we can start building a backlog with all such small todos, so we don't forget them.

**Comment by zhenfeizhang** [comment]
Criterion is fixed with
https://github.com/Manta-Network/pallet-manta-pay/commit/8fe3f4f3f0fcc64b1f166711052355f155575ec8

**Pull request merged**
