### PR TITLE
#13 CI/CD - Create initial github action to check compilation and formatting

### PR DESCRIPTION
**Pull request by ghzlatarev**
CI/CD : Create check.yml for compilation and formatting github action

* The check.yml first runs yamllint
* Then installs rustup and runs the following commands:
     cargo check --release
     cargo fmt --all -- --check
     cargo nightly clippy --release
     cargo test --release

### CODE REVIEW

**Comment by zhenfeizhang** [comment]
Problem fixed. Please merge `calamari` and rerun the CI

**Comment by ghzlatarev** [comment]
@stechu @zhenfeizhang  guys I think one of you needs to enable branch protection rules as I don't have access to the settings tab in this repository.
Currently I can merge without completed reviewers or passed CI/CD action.

**Comment by zhenfeizhang** [comment]
> @stechu @zhenfeizhang guys I think one of you needs to enable branch protection rules as I don't have access to the settings tab in this repository.
> Currently I can merge without completed reviewers or passed CI/CD action.



> Problem fixed. Please merge `calamari` and rerun the CI

I meant to say that I fixed the clippy bug in `calamari`. if you merge `calamari` to your local branch (which you don't need permission) you will see it. 

I am working on the new bugs in tests now.

**Comment by ghzlatarev** [comment]
> > @stechu @zhenfeizhang guys I think one of you needs to enable branch protection rules as I don't have access to the settings tab in this repository.
> > Currently I can merge without completed reviewers or passed CI/CD action.
> 
> > Problem fixed. Please merge `calamari` and rerun the CI
> 
> I meant to say that I fixed the clippy bug in `calamari`. if you merge `calamari` to your local branch (which you don't need permission) you will see it.
> 
> I am working on the new bugs in tests now.

Yes I got that and merged your changes in calamari in this branch.

My point was that currently this branch can be merged into calamari even though the action has failed and no reviewer has completed.
allowed_when_failed
This is not the case in the Manta repository and it has to be changed in the repository settings tab from what I understand from this article:
https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule
I don't have access to this "settings" tab.
no_settings

**Comment by zhenfeizhang** [comment]
Oh one more bug... with `cargo doc` this time. Fixed with be78ea402a13744252bc51efc40d8611c16aac21

**Comment by ghzlatarev** [comment]
> Oh one more bug... with `cargo doc` this time. Fixed with [be78ea4](https://github.com/Manta-Network/pallet-manta-pay/commit/be78ea402a13744252bc51efc40d8611c16aac21)

Yey all good now.

**Review by zhenfeizhang — APPROVED** [review]
LGTM.

**Comment by ghzlatarev** [comment]
> LGTM.

Still unable to merge the pull request. I think my account needs permissions in the protected branch https://docs.github.com/en/github/administering-a-repository/about-protected-branches
not_authorised

**Comment by zhenfeizhang** [comment]
right... Oh I see. Only @stechu and I are the committers to the main branch. I am merging now.

**Pull request merged**
